function GetExtraType(songtit)

	local ExtraSong = {
		--Extra Savior
		["IX"] = "Savior",
		["8000000"] = "Savior",
		["Adularia"] = "Savior",
		["Bakunana Testroyer"] = "Savior",
		["BeBeatStream"] = "Savior",
		["Cleopatrysm"] = "Savior",
		["Daily Lunch Special"] = "Savior",
		["Dopamine"] = "Savior",
		["Electric Dance System Music"] = "Savior",
		["Engraved Mark"] = "Savior",
		["Follow Tomorrow"] = "Savior",
		["FUJIMORI -Matsuri- FESTIVAL"] = "Savior",
		["Yakyuu no asobikata soshite sono rekishi ~ketteiban~"] = "Savior",
		["HYENA"] = "Savior",
		["Deadball de homerun"] = "Savior",
		["In The Breeze"] = "Savior",
		["Into the blue"] = "Savior",
		["JOMANDA"] = "Savior",
		["KHAMEN BREAK"] = "Savior",
		["Koi wa dou Moro Hadou OK Houteishiki!!"] = "Savior",
		["Mind Game"] = "Savior",
		["Nageki no ki"] = "Savior",
		["SUMMER DIARY -DDR mix-"] = "Savior",
		["Nostalgia Is Lost"] = "Savior",
		["Osenju meditation"] = "Savior",
		["Pa pi pu Yeah!"] = "Savior",
		["Poochie"] = "Savior",
		["POSSESSION(EDP Live Mix)"] = "Savior",
		["PUNISHER"] = "Savior",
		["Sakura Mirage"] = "Savior",
		["Sora e no katamichi kippu"] = "Savior",
		["Squeeze"] = "Savior",
		["Stella Sinistra"] = "Savior",
		["TECH-NOID"] = "Savior",
		["Tenkuu no hana"] = "Savior",
		["Totsugeki! Glass no kneeso hime!"] = "Savior",
		["Todoroke! Koi no beanball!!"] = "Savior",
		["True Blue"] = "Savior",
		["VEGA"] = "Savior",
		["Cytokinesis"] = "Savior",
		["S!ck"] = "Savior",
		["Illegal Function Call"] = "Savior",
		["STERLING SILVER"] = "Savior",
		["STERLING SILVER (U1 overground mix)"] = "Savior",
		["Far east nightbird"] = "Savior",
		["Far east nightbird kors k Remix -DDR edit ver-"] = "Savior",
		["Angelic Jelly"] = "Savior",
		["Grand Chariot"] = "Savior",
		["Sephirot"] = "Savior",
		["StrayedCatz"] = "Savior",
		["Triple Counter"] = "Savior",
		["ZEPHYRANTHES"] = "Savior",
		["Koisuru uchuu sensou!!"] = "Savior",
		["Renai kansoku"] = "Savior",
		["Oboro"] = "Savior",
		["Dadadadadadadadadada"] = "Savior",
		["CHOCOLATE PHILOSOPHY"] = "Savior",
		["High School Love"] = "Savior",
		["Shunpuu blowing wind"] = "Savior",
		["Sakura Reflection"] = "Savior",
		["Boss Rush"] = "Savior",
		["Plain Asia -PHQ remix-"] = "Savior",
		["Sennen no kotowari"] = "Savior",
		["Oboro (dj TAKA Remix)"] = "Savior",
		["Chronos (walk with you remix)"] = "Savior",
		["ALGORITHM"] = "Savior",
		["Eternal Summer"] = "Savior",
		["Life is beautiful"] = "Savior",
		["Puberty Dysthymia"] = "Savior",
		["Rejoin"] = "Savior",
		["SUPER SUMMER SALE"] = "Savior",
		["Fuurin hanabi"] = "Savior",
		["Seiza ga koishita shunkan wo"] = "Savior",
		["Prey"] = "Savior",
		--Extra Exclusive
		["IN BETWEEN"] = "Exclusive",
		["Love You More"] = "Exclusive",
		["Pursuer"] = "Exclusive",
		["Vanquish The Ghost"] = "Exclusive",
		["ACE FOR ACES"] = "Exclusive"
	}

	ExtraType = ExtraSong[songtit] or "StageDisplay"

	return ExtraType;
end;